---
-
  name: Update dao-chain binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop dao-chain service
    - name: Stop dao-chain service
      systemd:
        state: stopped
        name: dao-chain

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/0xDaoChain/dao-chain/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest dao-chain release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/dao-chain.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for dao-chain release
      file:
        path: /tmp/dao-chain
        state: directory

    ## unpack release tar
    - name: Unpack dao-chain release
      unarchive:
        remote_src: yes
        src: /tmp/dao-chain.tar.gz
        dest: /tmp/dao-chain

    ## set dao-chain to PATH
    - name: Place dao-chain binary to PATH
      copy:
        remote_src: yes
        src: /tmp/dao-chain/dao-chain
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp dao-chain release dir
      file:
        state: absent
        path: /tmp/dao-chain

    ## start dao-chain service
    - name: Start dao-chain service
      systemd:
        state: restarted
        name: dao-chain
        daemon_reload: yes
        enabled: yes